apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../template
nameSuffix: -midnight-monday
patches:
- target:
    group: batch
    version: v1
    kind: CronJob
    name: greeting
  path: ./patch.yaml
